api_version = "2026-04"

[[extensions]]
type = "ui_extension"
name = "Gift Message Checkout Block"
handle = "gift-message-checkout-block"
uid = "a8ba5cad-0315-3a1a-658c-d05b20a1b92c98fc308f"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.jsx"
default_placement = "INFORMATION3"
