# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5648b993ebb2c0c32aebf341a158f812"
name = "Gift Pulse: Gift Messages"
application_url = "https://qorve-2.duckdns.org"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "damian-xdcxxupp.myshopify.com"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://qorve-2.duckdns.org/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://qorve-2.duckdns.org/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ "write_products" ]

[auth]
redirect_urls = [ "https://qorve-2.duckdns.org/auth/callback" ]

[app_proxy]
url = "https://qorve-2.duckdns.org/proxy/gift-message"
subpath = "gift-message"
prefix = "apps"
