name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/shopify-dev-setup.mjs"
dev = "node scripts/shopify-dev-server.mjs"
