# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5648b993ebb2c0c32aebf341a158f812"
name = "Gift Message Bridge Lite"
application_url = "https://qorve-2.duckdns.org"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "https://qorve-2.duckdns.org/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "https://qorve-2.duckdns.org/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "https://qorve-2.duckdns.org/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [ "https://qorve-2.duckdns.org/auth/callback" ]

[app_proxy]
url = "https://qorve-2.duckdns.org/proxy/gift-message"
subpath = "gift-message"
prefix = "apps"
